yandex:
  service: S3
  access_key_id: <%= ENV["YNDX_ACCESS_KEY_ID"] %>
  secret_access_key: <%= ENV["YNDX_SECRET_ACCESS_KEY"] %>
  region: ru-central1
  bucket: grizzledbearteam
  endpoint: https://storage.yandexcloud.net
